
const FETCH_RECORDS = 'RECORDS/FETCH_RECORDS';
const ADD_NEW_RECORD = 'RECORDS/ADD_NEW_RECORD';

const SIGN_UP = 'AUTH/SIGN_UP';
const SIGN_IN = 'AUTH/SIGN_IN';
const SIGN_OUT = 'AUTH/SIGN_OUT';
const AUTH_STATE_CHANGED = 'AUTH/AUTH_STATE_CHANGED';

const SAVE_SETTINGS = 'SETTINGS/SAVE_SETTINGS';
const GET_SETTINGS = 'SETTINGS/GET_SETTINGS';

export default {
    FETCH_RECORDS,
    ADD_NEW_RECORD,
    SIGN_UP,
    SIGN_IN,
    SIGN_OUT,
    AUTH_STATE_CHANGED,
    SAVE_SETTINGS,
    GET_SETTINGS
}
